### ISSUE TITLE
Possible Unhandled Promise Rejection (id: 0): TypeError: Object is not async iterable

### ISSUE THREAD

**Issue by uloco** [LinusU/react-native-get-random-values#47]
After installing this library (to get redux-devtools/remote to work) I am getting this warning in a react native app when starting / reloading. 

```
 WARN  Possible Unhandled Promise Rejection (id: 2):
TypeError: Object is not async iterable
TypeError: Object is not async iterable
    at _asyncIterator (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=world.smokeless.ios.dev:216651:432)
    at ?anon_0_ (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=world.smokeless.ios.dev:216807:49)
    at next (native)
    at asyncGeneratorStep (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=world.smokeless.ios.dev:6709:26)
    at _next (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=world.smokeless.ios.dev:6728:29)
    at anonymous (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=world.smokeless.ios.dev:6733:14)
    at tryCallTwo (/Users/distiller/react-native/sdks/hermes/build_iphonesimulator/lib/InternalBytecode/InternalBytecode.js:61:9)
    at doResolve (/Users/distiller/react-native/sdks/hermes/build_iphonesimulator/lib/InternalBytecode/InternalBytecode.js:216:25)
    at Promise (/Users/distiller/react-native/sdks/hermes/build_iphonesimulator/lib/InternalBytecode/InternalBytecode.js:82:14)
    at anonymous (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=world.smokeless.ios.dev:6725:25)
    at anonymous (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=world.smokeless.ios.dev:216827:11)
    at anonymous (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=world.smokeless.ios.dev:216868:38)
    at apply (native)
    at anonymous (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=world.smokeless.ios.dev:156383:38)
    at createStore (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=world.smokeless.ios.dev:156127:35)
    at _configureStore (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=world.smokeless.ios.dev:157534:42)
    at anonymous (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=world.smokeless.ios.dev:183300:85)
    at loadModuleImplementation (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=world.smokeless.ios.dev:252:14)
    at guardedLoadModule (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=world.smokeless.ios.dev:160:38)
    at metroRequire (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=world.smokeless.ios.dev:84:92)
    at anonymous (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=world.smokeless.ios.dev:143652:14)
    at loadModuleImplementation (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=world.smokeless.ios.dev:252:14)
    at guardedLoadModule (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=world.smokeless.ios.dev:153:47)
    at metroRequire (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=world.smokeless.ios.dev:84:92)
    at anonymous (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=world.smokeless.ios.dev:1140:23)
    at componentProviderInstrumentationHook (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=world.smokeless.ios.dev:59169:21)
    at run (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=world.smokeless.ios.dev:59197:79)
    at runApplication (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=world.smokeless.ios.dev:59248:28)
    at apply (native)
    at __callFunction (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=world.smokeless.ios.dev:18806:36)
    at anonymous (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=world.smokeless.ios.dev:18567:31)
    at __guard (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=world.smokeless.ios.dev:18757:15)
    at callFunctionReturnFlushedQueue (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=world.smokeless.ios.dev:18566:21)
```

I imported it in `index.js` and installed pods like described in the readme.
Do you have any idea how to fix this? Anyone else have the same issue?

**Comment by uloco** [comment]
could this be the reason?
https://github.com/facebook/hermes/issues/1089

**Comment by uloco** [comment]
looks like this needs to be fixed on another end.
